apiVersion: v1
kind: Namespace
metadata:
  name: names-api

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: names-api
  namespace: names-api
spec:
  replicas: 3
  selector:
    matchLabels:
      name: names-api-pod
  template:
    metadata:
      labels:
        name: names-api-pod
    spec:
      containers:
        - name: names-api
          image: clusterkuberegistry.azurecr.io/names-api:v3.1
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: names-api-svc
  namespace: names-api
spec:
  selector:
    name: names-api-pod
  ports:
    - protocol: TCP
      port: 80

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: names-api-ing
  namespace: names-api
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - http:
        paths:
          - path: /name$
            backend:
              serviceName: names-api-svc
              servicePort: 80